---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  require_chef_omnibus: 11.8.0
  attributes:
    postgresql:
      version: "9.3"
      password:
        postgres: postgres
      server:
        service_name: postgresql-9.3
      config:
        port: 5432

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[postgresql::server]
      - recipe[whats-fresh::default]
    attributes:
      whats_fresh:
        make_db: true
        debug: false
  - name: develop
    run_list:
      - recipe[postgresql::server]
      - recipe[whats-fresh::default]
    attributes:
      whats_fresh:
        make_db: true
        debug: true
  - name: both
    run_list:
      - recipe[postgresql::server]
      - recipe[whats-fresh::default]
      - recipe[working-waterfronts::default]
    attributes:
      whats_fresh:
        make_db: true
        debug: true
      working_waterfronts:
        debug: true
        make_db: true