---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>
  floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] %>

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    postgresql:
      version: "9.3"
      password:
        postgres: postgres
      server:
        service_name: postgresql-9.3
      config:
        port: 5432
    authorization:
      sudo:
        users:
          - vagrant
          - centos
          - ubuntu
          - fedora
    omnibus_updater:
      disabled: true

platforms:
- name: centos-6.6
  driver_plugin: openstack
  driver_config:
    username: centos
    image_ref: "CentOS 6.6"


suites:
  - name: default
    run_list:
      - recipe[whats-fresh::_centos]
      - recipe[postgresql::server]
      - recipe[postgis::default]
      - recipe[whats-fresh::database]
      - recipe[whats-fresh::default]
      - recipe[whats-fresh::nginx]
    attributes:
      whats_fresh:
        debug: false
  - name: develop
    run_list:
      - recipe[whats-fresh::_centos]
      - recipe[postgresql::server]
      - recipe[postgis::default]
      - recipe[whats-fresh::database]
      - recipe[whats-fresh::default]
      - recipe[whats-fresh::nginx]
    attributes:
      whats_fresh:
        debug: true
  - name: both
    run_list:
      - recipe[whats-fresh::_centos]
      - recipe[postgresql::server]
      - recipe[whats-fresh::database]
      - recipe[whats-fresh::default]
      - recipe[whats-fresh::nginx]
      - recipe[working-waterfronts::default]
    attributes:
      whats_fresh:
        debug: true
      working_waterfronts:
        debug: true
        make_db: true
