---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  require_chef_omnibus: 11.8.0
  attributes:
    postgresql:
      version: "9.3"
      password:
        postgres: postgres
      server:
        service_name: postgresql-9.3
      config:
        port: 5432

platforms:
  - name: centos-6.6

suites:
  - name: whats_fresh
    run_list:
      - recipe[postgresql::server]
      - recipe[whats-fresh::whats_fresh]
    attributes:
      whats_fresh:
        make_db: true
        debug: true
  - name: working_waterfronts
    run_list:
      - recipe[postgresql::server]
      - recipe[whats-fresh::working_waterfronts]
    attributes:
      whats_fresh:
        make_db: true
        debug: true
