source 'https://supermarket.getchef.com'

metadata
cookbook 'build-essential'
cookbook 'database'
cookbook 'firewall', git: 'git@github.com:osuosl-cookbooks/firewall'
cookbook 'geos'
cookbook 'git'
cookbook 'magic_shell'
cookbook 'osl-nginx', git: 'git@github.com:osuosl-cookbooks/osl-nginx'
cookbook 'postgis'
cookbook 'postgresql'
cookbook 'python'
cookbook 'python-webapp', git: 'git@github.com:osuosl-cookbooks/python-webapp'
cookbook 'selinux_policy'
cookbook 'yum-epel'
cookbook 'yum-ius'
cookbook 'yum-osuosl'
cookbook 'monitoring', git: 'git@github.com:osuosl-cookbooks/monitoring'
cookbook 'osl-munin', git: 'git@github.com:osuosl-cookbooks/osl-munin'
cookbook 'osl-nagios', git: 'git@github.com:osuosl-cookbooks/osl-nagios'
cookbook 'osl-apache', git: 'git@github.com:osuosl-cookbooks/osl-apache'
cookbook 'osl-nrpe', git: 'git@github.com:osuosl-cookbooks/osl-nrpe'
