name 'whats-fresh'
maintainer 'Oregon State University'
maintainer_email 'systems@osuosl.org'
license 'Apache 2.0'
description "Installs/Configures What's Fresh dependencies"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.16'

depends 'build-essential'
depends 'database'
depends 'geos'
depends 'git'
depends 'magic_shell'
depends 'osl-nginx'
depends 'postgis'
depends 'postgresql'
depends 'python'
depends 'python-webapp'
depends 'selinux_policy'
depends 'yum'
depends 'yum-epel'
depends 'yum-ius'
depends 'yum-osuosl'
